apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
  labels:
    name: result-service
    app: vote-app
spec:
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31001
  selector:
    name: result-pods
    app: vote-app
  type: NodePort
  