apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote
  labels:
    name: vote-deploy
    app: vote-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote-pods
      app: vote-app
  template:
    metadata:
      name: vote-pod
      labels:
        name: vote-pods
        app: vote-app
    spec:
      containers:
        - name: vote-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80

    