apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
  labels:
    name: vote-service
    app: vote-app
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    name: vote-pods
    app: vote-app
  type: NodePort
  