apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
  labels:
    name: worker-deploy
    app: vote-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pods
      app: vote-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pods
        app: vote-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker


    