version: '2'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - todonet

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - todonet
  
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - todonet
    volumes:
      - mongo-data:/data/db
  
  db-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - todonet
  
volumes:
  mongo-data:

networks:
  todonet:

